packages:
  - ./
  - cli
  - docs
  - layer
  - playground

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - '@vercel/speed-insights'
  - better-sqlite3
  - sharp
